name: NPM Publish

on:
  push:
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn
      - run: yarn test
      - run: yarn build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
      - run: yarn build
      - name: Publish dist files
        run: ls && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}